- name: Install docker-compose python package
  pip:
    name:
    - docker<7.0
    - docker-compose

- name: Git checkout
  git:
    repo: "{{ https://github.com/szymonov3/App_of_apps.git }}"
    dest: "{{ deployment_path }}"
    version: "{{ git_branch }}"

- name: Run `docker-compose up`
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes
